import { typeAssert } from 'type-assertions/index';
import { map, reduce, filter, add, subtract, prop, pipe } from './index';
const mapResult1 = map()(String)()([1, 2, 3]);
typeAssert();
const mapResult2 = map(Boolean, [1, 0, 1]);
typeAssert();
const reduceResult1 = reduce()((a, b) => a + b)()(0)()([1, 2, 3]);
typeAssert();
const reduceResult2 = reduce(add, 0, [1, 2, 3]);
typeAssert();
const reduceResult3 = reduce(subtract, 0, [1, 2, 3]);
typeAssert();
const reduceResult4 = reduce((a, b) => a + b, '', ['1', '2', '3']);
typeAssert();
const filterResult1 = filter()((n) => n !== 0)()([0, 1, 2]);
typeAssert();
const filterResult2 = filter(Boolean, [0, 1, 2]);
typeAssert();
const addResult1 = add()(1)()(2);
typeAssert();
const addResult2 = add(1, 2);
typeAssert();
const subtractResult1 = subtract()(2)()(1);
typeAssert();
const subtractResult2 = subtract(2, 1);
typeAssert();
const propResult1 = prop()('x')()({ x: 1, y: 'Hello' });
typeAssert();
const propResult2 = prop('y', { x: 1, y: 'Hello' });
typeAssert();
const pipeResult1 = pipe(filter(Boolean), map(String), reduce((a, b) => a + b, ''))([0, 1, 2, 3]);
typeAssert();
const pipeResult2 = pipe()()(filter(Boolean), map(String))([0, 1, 2, 3]);
typeAssert();
